name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train_development:
    runs-on: ubuntu-latest
    environment: 
      name: development
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute job on Azure Machine Learning
        working-directory: src/
        run: az ml job create --file train_development-data.yml -g rg-challengue-02 -w mlw-challengue-02

  train_production:
    runs-on: ubuntu-latest
    needs: train_development
    environment: 
      name: production
    steps:
      - name: Check out repo
        uses: actions/checkout@main

      - name: Install az ml extension
        run: az extension add -n ml -y

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Execute job on Azure Machine Learning
        working-directory: src/
        run: az ml job create --file train_production-data.yml -g rg-challenge-05 -w mlw-challenge-05
