name: Code check workflow

on:
  push:
    branches:
      - main

jobs:
  code_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Will add code checks here in next challenge"
